"""Emit `zg_params.h` from the same calibration files the Python filter loads.

The firmware must not carry its own copy of the constants. If it did, the C and the Python
could drift apart silently and every bit-exactness claim in E14 would be measuring nothing.
So the header is generated, and `e14_firmware.py` regenerates it before every build.
"""
import os, sys, json
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import numpy as np
from safe_charge.rom import load_params, _OCV_SOC, _OCV_V

HERE = os.path.dirname(os.path.abspath(__file__))
N_OCV = 128                      # uniform resample; E13 sized the table at this


def main():
    p = load_params()
    a0, a3, Ea, A, cT, i0_0, i0_1 = p["eta_params"]
    soc = np.linspace(0.0, 1.0, N_OCV)
    ocv = np.interp(soc, _OCV_SOC, _OCV_V)
    L = [
        "/* Generated by firmware/gen_params.py -- do not edit. */",
        "#ifndef ZG_PARAMS_H", "#define ZG_PARAMS_H", "",
        f"#define ZG_N_OCV {N_OCV}", "",
    ]
    for k, v in (("A0", a0), ("A3", a3), ("EA", Ea), ("AACT", A), ("CT", cT),
                 ("I0_0", i0_0), ("I0_1", i0_1),
                 ("R1_FRAC", p["R1_frac"]), ("TAU1", p["tau1"]), ("DUDT", p["dUdT"]),
                 ("C_TH", p["C_th"]), ("HA", p["hA"]), ("Q_NOM", p["Q_nom"]),
                 ("PL_P0A", p["pl_p0a"]), ("PL_P0B", p["pl_p0b"]), ("PL_P0C", p["pl_p0c"]),
                 ("PL_P0D", p["pl_p0d"]), ("PL_P1A", p["pl_p1a"]), ("PL_P1B", p["pl_p1b"]),
                 ("PL_P1C", p["pl_p1c"]), ("PL_ET", p["pl_ET"]),
                 ("PLATE_MARGIN", p["plating_margin_V"]), ("TREF", 298.15)):
        L.append(f"#define ZG_{k} ({v!r}f)".replace("e-0", "e-").replace("e+0", "e"))
    L += ["", "static const float zg_ocv[ZG_N_OCV] = {"]
    for i in range(0, N_OCV, 6):
        L.append("    " + " ".join(f"{v:.7f}f," for v in ocv[i:i + 6]))
    L += ["};", "", "#endif"]
    out = os.path.join(HERE, "zg_params.h")
    open(out, "w").write("\n".join(L) + "\n")
    print(f"wrote {out}  ({N_OCV} OCV entries)")


if __name__ == "__main__":
    main()
